name: Test code and publish package

on:
  push:

jobs:
  deploy_win_64_cuda11:
    strategy:
      fail-fast: false
      matrix:
        config_file:
          [
            "conda_package/variants/win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.22python3.10.____cpython.yaml",
          ]
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          activate-environment: ../deploy-env
          python-version: "3.10"
          channels: conda-forge

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup CUDA Toolkit
        id: cuda-toolkit
        shell: pwsh
        run: conda_package/scripts/setup_cuda.ps1
        env:
          INPUT_CUDA_VERSION: 11.8.0

      - name: Build openmm package
        shell: bash -l {0}
        run: |
          git config --global --add safe.directory '*'
          conda install anaconda-client conda-build
          conda clean --all -y
          conda build conda_package/recipe/ --variant-config-files ${{ matrix.config_file }} --output-folder ./pkg/ --no-include-recipe --no-anaconda-upload -c conda-forge
        env:
          OPENMM_VERSION: ${{ github.ref_name }}
          OPENMM_COMMIT: ${{ github.sha }}
